<?php
$data['fwicon']['toggle-sidebar']="fa-solid fa-layer-group";   //header Toggle Sidebar
$data['fwicon']['home']="fa-solid fa-warehouse";               //Dashboard
$data['fwicon']['sales-volume']="fa-solid fa-sack-dollar";     //Add Money
$data['fwicon']['arrow-right-arrow-left']="fa-solid fa-arrow-right-arrow-left"; //Transfer
$data['fwicon']['requestfund']="fa-solid fa-hand-holding-dollar"; //Request Money
$data['fwicon']['transaction']="fa-solid fa-rectangle-list";   //Transaction list
$data['fwicon']['mystatement']="fa-solid fa-file-invoice-dollar"; //My Statement
$data['fwicon']['beneficiary']="fa-solid fa-user-group";       // Beneficiary
$data['fwicon']['letter']="fa-solid fa-envelope-open-text";    //Reference Latter 
$data['fwicon']['security']="fa-solid fa-shield-halved";       //shield 
$data['fwicon']['profile']="fa-solid fa-user-tie";             //Profile
$data['fwicon']['comp-profile']="fa-solid fa-address-card";    //Company Profile
$data['fwicon']['reset-password']="fa-solid fa-lock";          //Password 
$data['fwicon']['history']="fa-solid fa-circle-info";          //info
$data['fwicon']['signout']="fa-solid fa-power-off";            //signout
$data['fwicon']['key']="fa-solid fa-key";                      //key
$data['fwicon']['edit']="fa-solid fa-pen-to-square";           //Edit
$data['fwicon']['delete']="fa-solid fa-trash-can"; 			   //Delete
$data['fwicon']['display']="fa-solid fa-binoculars";           //display
$data['fwicon']['check']="fa-solid fa-check-double";
$data['fwicon']['circle-info']="fa-solid fa-circle-info";      //circle info
$data['fwicon']['submit']="fa-regular fa-circle-check";        // circle check on button
$data['fwicon']['amount']="fa-solid fa-circle-dollar-to-slot"; //Transaction list fas fa-money-bill-alt 
$data['fwicon']['settlement']="fa-solid fa-hand-holding-hand"; //settlement
$data['fwicon']['refund']="fa-solid fa-arrows-spin";           // Refund
$data['fwicon']['deshboard-website']="fa-solid fa-book-atlas"; //For Deshboard Website
$data['fwicon']['calender']="fa-solid fa-calendar-days";       //calender
$data['fwicon']['tick-circle']="fa-solid fa-circle-check";     //Check Circle
$data['fwicon']['check-cross']="fa-solid fa-circle-xmark";     //check cross 
$data['fwicon']['amazon-pay']="fa-brands fa-amazon-pay";       // thumbs-up
$data['fwicon']['check-circle']="fa-regular fa-circle-check";  //check circle
$data['fwicon']['circle-cross']="fa-regular fa-circle-xmark";  //circle cross
$data['fwicon']['spinner']="fa-solid fa-spinner";
$data['fwicon']['copy']="fa-solid fa-copy"; //Copy
$data['fwicon']['download']="fa-solid fa-download"; //download
$data['fwicon']['mobile-screen']="fa-solid fa-mobile-screen"; // mobile-screen  
$data['fwicon']['triangle-exclamation']="fa-solid fa-triangle-exclamation"; // triangle-exclamation
$data['fwicon']['bank']="fa-solid fa-landmark";
$data['fwicon']['rupee']="fa-solid fa-indian-rupee-sign";
$data['fwicon']['setting']="fa-solid fa-gear";    //website
$data['fwicon']['users']="fa-solid fa-users-line";
$data['fwicon']['fees']="fa-solid fa-file-invoice-dollar";
$data['fwicon']['email-open']="fa-solid fa-envelope-open"; //Email Template
$data['fwicon']['circle-dot']="fa-solid fa-circle-dot";    //circle dot
$data['fwicon']['credit']="fa-solid fa-hand-holding-dollar"; //Request Fund
$data['fwicon']['all-transaction']="fa-solid fa-hand-holding-hand"; //settlement
$data['fwicon']['hand']="fa-solid fa-hand-point-right"; //Hand Point Right
$data['fwicon']['eye']="fa-regular fa-eye"; //Eye
$data['fwicon']['circle-plus']="fa-solid fa-circle-plus"; // circle-plus
$data['fwicon']['back']="fa-solid fa-backward";    //back
$data['fwicon']['verified']="fa-regular fa-circle-check"; //verified
$data['fwicon']['search']="fa-solid fa-magnifying-glass"; //Search
$data['fwicon']['eye']="fa-regular fa-eye"; //Eye
$data['fwicon']['pdf']="fa-solid fa-file-pdf";     //pdf
$data['fwicon']['excel']="fa-solid fa-file-excel"; //excel
$data['fwicon']['support']="fa-solid fa-headset";
$data['fwicon']['email']="fa-solid fa-envelope"; //Email
$data['fwicon']['phone']="fa-solid fa-phone"; //phone
$data['fwicon']['bitcoin']="fa-brands fa-bitcoin"; //bitcoin
$data['fwicon']['user-shield']="fa-solid fa-user-shield"; //KYC
$data['fwicon']['Default']="fa-solid fa-globe"; //Default
$data['fwicon']['card-trensfer']="fa-solid fa-money-bill-transfer"; //card-trensfer
$data['fwicon']['add-account']="fa-solid fa-user-plus"; //Add Account
$data['fwicon']['user-details']="fa-solid fa-clipboard-user"; //User Details
$data['fwicon']['links']="fa-solid fa-paperclip"; //links
$data['fwicon']['rotate']="fa-solid fa-arrows-rotate"; //refresh
$data['fwicon']['star']="fa-solid fa-star-of-life"; //star
$data['fwicon']['pen']="fa-solid fa-pen"; //pen

$data['fwicon']['facebook']="fa-brands fa-facebook"; //facebook
$data['fwicon']['linkedin']="fa-brands fa-linkedin"; //linkedin 
$data['fwicon']['google']="fa-brands fa-google"; //linkdin

$data['fwicon']['bank']="fa-solid fa-building-columns"; //bank
$data['fwicon']['wallet']="fa-solid fa-wallet"; //wallet
$data['fwicon']['email']="fa-solid fa-envelope"; //Email
$data['fwicon']['phone']="fa-solid fa-phone"; //phone
$data['fwicon']['bitcoin']="fa-brands fa-bitcoin"; //bitcoin
$data['fwicon']['credit-card']="fa-regular fa-credit-card"; //creditcard
$data['fwicon']['square-link']="fa-solid fa-arrow-up-right-from-square"; //creditcard
?>